# Generated by Django 5.1.2 on 2024-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="生年月日"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tel_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="電話番号"
            ),
        ),
    ]
