# Generated by Django 5.1.2 on 2024-11-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="フォローされる人",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="フォローする人",
                    ),
                ),
            ],
            options={
                "verbose_name": "フォロー関係",
                "verbose_name_plural": "フォロー関係",
                "db_table": "follow_relation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "followee"),
                        name="unique_follower_followee_relation",
                    )
                ],
            },
        ),
    ]
