# Generated by Django 5.1.2 on 2024-11-21 13:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_followrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="名前"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="header_image",
            field=models.ImageField(
                blank=True,
                upload_to=accounts.models.header_image_path,
                verbose_name="ヘッダー画像",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                upload_to=accounts.models.icon_image_path,
                verbose_name="アイコン画像",
            ),
        ),
    ]
