# Generated by Django 5.1.2 on 2024-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_name_alter_customuser_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="description",
            field=models.TextField(blank=True, max_length=160, verbose_name="自己紹介"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=30, verbose_name="場所"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="website",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ウェブサイト"
            ),
        ),
    ]
