# Generated by Django 5.1.2 on 2024-11-24 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0002_comment_like_retweet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "tweet"), name="unique_like_relation"
            ),
        ),
        migrations.AddConstraint(
            model_name="retweet",
            constraint=models.UniqueConstraint(
                fields=("user", "tweet"), name="unique_retweet_relation"
            ),
        ),
    ]
