# Generated by Django 5.1.2 on 2024-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0004_alter_comment_user_alter_like_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=140, verbose_name="ツイート内容"),
        ),
    ]
