# Generated by Django 5.1.2 on 2024-12-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0006_alter_tweet_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tweets.tweet",
            ),
        ),
    ]
