# Generated by Django 5.1.2 on 2025-01-12 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="unique_message_relation",
        ),
    ]
